# Generated by Django 5.2.17 on 2026-09-02 07:37

import dbs.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.SlugField(max_length=64, unique=True)),
                ("host", models.CharField(max_length=255)),
                ("port", models.PositiveIntegerField(default=22)),
                ("username", models.CharField(max_length=128)),
                ("remote_dir", models.CharField(default=".", max_length=512)),
                (
                    "auth_method",
                    models.CharField(
                        choices=[
                            ("agent", "SSH agent"),
                            ("key_file", "Private key file on the server"),
                            ("key_material", "Private key pasted here"),
                            ("password", "Password"),
                        ],
                        default="agent",
                        max_length=16,
                    ),
                ),
                (
                    "key_filename",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "known_hosts",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("auto_add_host_key", models.BooleanField(default=False)),
                ("connect_timeout", models.FloatField(default=30.0)),
                ("is_default", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, default="")),
                ("secret_password", dbs.models.SecretField(blank=True, default="")),
                ("secret_key_material", dbs.models.SecretField(blank=True, default="")),
                (
                    "secret_key_passphrase",
                    dbs.models.SecretField(blank=True, default=""),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "SFTP target",
                "verbose_name_plural": "SFTP targets",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="BackupRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("size_bytes", models.BigIntegerField(default=0)),
                ("sha256", models.CharField(blank=True, default="", max_length=64)),
                ("location", models.CharField(blank=True, default="", max_length=1024)),
                ("prefix", models.CharField(default="backup", max_length=64)),
                ("database", models.CharField(default="default", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("note", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dbs.backuptarget",
                    ),
                ),
            ],
            options={
                "verbose_name": "backup",
                "verbose_name_plural": "backups",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="KnownLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(default="usual", max_length=64)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("radius_km", models.FloatField(default=50.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dbs_locations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("user_id", "label"),
            },
        ),
        migrations.CreateModel(
            name="Lockout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dbs_lockout",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SecurityPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("configured", models.BooleanField(default=False)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("relaxed", "Relaxed"),
                            ("balanced", "Balanced"),
                            ("strict", "Strict"),
                            ("paranoid", "Paranoid"),
                        ],
                        default="balanced",
                        max_length=16,
                    ),
                ),
                ("expected_networks", models.TextField(blank=True, default="")),
                ("trusted_networks", models.TextField(blank=True, default="")),
                ("warn_threshold", models.FloatField(default=0.6)),
                ("logout_threshold", models.FloatField(default=0.85)),
                ("learning_logins", models.PositiveIntegerField(default=10)),
                ("idle_timeout_minutes", models.PositiveIntegerField(default=120)),
                ("collect_location", models.BooleanField(default=False)),
                ("notify_emails", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "configured_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "security policy",
                "verbose_name_plural": "security policy",
            },
        ),
        migrations.CreateModel(
            name="AnomalyEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField(default=0.0)),
                ("reasons", models.JSONField(default=list)),
                ("action_taken", models.CharField(default="warn", max_length=16)),
                (
                    "remote_addr",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dbs_anomalies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="dbs_anomaly_user_id_f783ef_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=64)),
                (
                    "target_name",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("detail", models.TextField(blank=True, default="")),
                (
                    "remote_addr",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("succeeded", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="dbs_auditev_created_632071_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SessionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("kind", models.CharField(default="request", max_length=32)),
                (
                    "remote_addr",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("ip_prefix", models.CharField(blank=True, default="", max_length=64)),
                ("ua_hash", models.CharField(blank=True, default="", max_length=64)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("accuracy_m", models.FloatField(blank=True, null=True)),
                ("features", models.JSONField(default=dict)),
                ("score", models.FloatField(default=0.0)),
                ("verdict", models.CharField(default="ok", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dbs_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="dbs_session_user_id_eae497_idx",
                    )
                ],
            },
        ),
    ]
