# Generated by Django 5.2.17 on 2026-10-04 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dbs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Panel",
            fields=[],
            options={
                "verbose_name": "DBS panel",
                "verbose_name_plural": "DBS panel",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("dbs.securitypolicy",),
        ),
    ]
