# Generated by Django 6.1.2 on 2026-10-09 14:15

from django.conf import settings
from django.db import migrations, models
from django.db.models import F


def backfill_outcome(apps, schema_editor):
    AuditEvent = apps.get_model("dbs", "AuditEvent")
    events = AuditEvent.objects.using(schema_editor.connection.alias)
    events.filter(succeeded=False).update(status="failed")
    events.update(started_at=F("created_at"), finished_at=F("created_at"))


class Migration(migrations.Migration):

    dependencies = [
        ("dbs", "0002_panel"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auditevent",
            name="data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="error_code",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("running", "Running"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                ],
                default="succeeded",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="subject",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="target_name",
            field=models.CharField(blank=True, default="", max_length=1024),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["status", "-created_at"], name="dbs_auditev_status_f65f33_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["action", "-created_at"], name="dbs_auditev_action_ff95cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["subject", "-created_at"], name="dbs_auditev_subject_b3f0bc_idx"
            ),
        ),
        migrations.RunPython(backfill_outcome, migrations.RunPython.noop),
    ]
