import type { CopyKey, Lang } from './copy.types';

export const COPY = {
  // The shell
  skipToContent: { en: 'Skip to content', ar: 'الانتقال إلى المحتوى' },
  language: { en: 'Language', ar: 'اللغة' },
  navDashboard: { en: 'Dashboard', ar: 'لوحة المتابعة' },
  navServers: { en: 'Servers', ar: 'الخوادم' },
  navActivity: { en: 'Activity', ar: 'النشاط' },
  signOut: { en: 'Sign out', ar: 'تسجيل الخروج' },
  aboutDbs: { en: 'About DBS', ar: 'حول DBS' },

  // First run
  setupTitle: { en: 'Create your account', ar: 'إنشاء الحساب' },
  setupKey: { en: 'Setup key', ar: 'مفتاح الإعداد' },
  confirmPassword: { en: 'Confirm password', ar: 'تأكيد كلمة المرور' },
  createAccount: { en: 'Create account', ar: 'إنشاء الحساب' },
  passwordsDiffer: { en: 'The passwords do not match.', ar: 'كلمتا المرور غير متطابقتين.' },

  // Sign in
  signInTitle: { en: 'Sign in', ar: 'تسجيل الدخول' },
  username: { en: 'Username', ar: 'اسم المستخدم' },
  password: { en: 'Password', ar: 'كلمة المرور' },
  serverPassword: { en: 'Server password', ar: 'كلمة مرور الخادم' },
  signIn: { en: 'Sign in', ar: 'تسجيل الدخول' },
  wrongCredentials: {
    en: 'The username or password is not correct.',
    ar: 'اسم المستخدم أو كلمة المرور غير صحيحة.',
  },
  tooManyAttempts: {
    en: 'Too many attempts. Wait a few minutes and try again.',
    ar: 'محاولات كثيرة. انتظر بضع دقائق ثم حاول مرة أخرى.',
  },
  enterPassword: { en: 'Enter your password.', ar: 'أدخل كلمة المرور.' },

  // Servers list
  serversTitle: { en: 'Servers', ar: 'الخوادم' },
  addServer: { en: 'Add server', ar: 'إضافة خادم' },

  // Add server wizard
  wizardTitle: { en: 'Add a server', ar: 'إضافة خادم' },
  stepSnippet: { en: 'Connection snippet', ar: 'بيانات الاتصال' },
  stepAddress: { en: 'Address and host key', ar: 'العنوان ومفتاح المضيف' },
  stepSignIn: { en: 'Sign-in', ar: 'طريقة الدخول' },
  stepProject: { en: 'Project', ar: 'المشروع' },
  stepCheck: { en: 'Check', ar: 'الفحص' },
  stepPassphrase: { en: 'Backup passphrase', ar: 'عبارة مرور النسخ الاحتياطية' },
  stepTestBackup: { en: 'Test backup', ar: 'نسخة احتياطية تجريبية' },
  snippetInvalid: {
    en: 'This is not valid JSON. Paste the whole snippet.',
    ar: 'هذا النص ليس JSON صالحا. الصق بيانات الاتصال كاملة.',
  },
  name: { en: 'Name', ar: 'الاسم' },
  host: { en: 'Host', ar: 'المضيف' },
  port: { en: 'Port', ar: 'المنفذ' },
  next: { en: 'Next', ar: 'التالي' },
  edit: { en: 'Edit', ar: 'تعديل' },
  saveChanges: { en: 'Save changes', ar: 'حفظ التغييرات' },
  changesSaved: { en: 'Changes saved.', ar: 'تم حفظ التغييرات.' },
  fillIn: { en: 'Fill in this field.', ar: 'املأ هذا الحقل.' },
  portRange: { en: 'Enter a port from 1 to 65535.', ar: 'أدخل منفذا من 1 إلى 65535.' },
  getHostKey: { en: 'Get host key', ar: 'جلب مفتاح المضيف' },
  getHostKeyFirst: { en: 'Get the host key first.', ar: 'اجلب مفتاح المضيف أولا.' },
  fingerprintsMatch: { en: 'The fingerprints match', ar: 'البصمتان متطابقتان' },
  compareFirst: { en: 'Compare the fingerprints first.', ar: 'قارن البصمتين أولا.' },
  addServerSubmit: { en: 'Add server', ar: 'إضافة الخادم' },
  serverAdded: { en: 'Server added.', ar: 'تمت إضافة الخادم.' },
  findProject: { en: 'Find the project', ar: 'البحث عن المشروع' },
  projectFolder: { en: 'Project folder', ar: 'مجلد المشروع' },
  pythonCommand: { en: 'Python command', ar: 'أمر Python' },
  remoteBackupFolder: { en: 'Remote backup folder', ar: 'مجلد النسخ الاحتياطية على الخادم' },
  allowedFolders: { en: 'Allowed folders', ar: 'المجلدات المسموح بها' },
  remove: { en: 'Remove', ar: 'إزالة' },
  envFile: { en: '.env file', ar: 'ملف متغيرات البيئة' },
  versionsWork: { en: 'The two versions work together.', ar: 'الإصداران متوافقان.' },
  readPassphrase: { en: 'Read it from the server', ar: 'قراءتها من الخادم' },
  passphraseSaved: { en: 'The backup passphrase is saved.', ar: 'تم حفظ عبارة مرور النسخ الاحتياطية.' },
  takeTestBackup: { en: 'Take a test backup', ar: 'أخذ نسخة احتياطية تجريبية' },
  testBackupWorked: { en: 'The test backup worked.', ar: 'نجحت النسخة الاحتياطية التجريبية.' },
  openServer: { en: 'Open the server', ar: 'فتح الخادم' },

  // Server page
  tabOverview: { en: 'Overview', ar: 'نظرة عامة' },
  tabBackups: { en: 'Backups', ar: 'النسخ الاحتياطية' },
  tabFiles: { en: 'Files', ar: 'الملفات' },
  tabEnv: { en: '.env file', ar: 'ملف متغيرات البيئة' },
  tabActivity: { en: 'Activity', ar: 'النشاط' },
  serverSections: { en: 'Server sections', ar: 'أقسام الخادم' },
  ready: { en: 'Ready', ar: 'جاهز' },
  checkNow: { en: 'Check now', ar: 'فحص الآن' },
  system: { en: 'System', ar: 'النظام' },
  dbsVersion: { en: 'django-dbs version', ar: 'إصدار django-dbs' },
  backupCommand: { en: 'Backup command', ar: 'أمر النسخ الاحتياطي' },
  found: { en: 'Found', ar: 'موجود' },
  reviewHostKey: { en: 'Review host key', ar: 'مراجعة مفتاح المضيف' },
  showPassphrase: { en: 'Show passphrase', ar: 'إظهار عبارة المرور' },
  hidePassphrase: { en: 'Hide passphrase', ar: 'إخفاء عبارة المرور' },
  passphrase: { en: 'Passphrase', ar: 'عبارة المرور' },
  yourPassword: { en: 'Your password', ar: 'كلمة المرور' },
  wrongPassword: { en: 'The password is not correct.', ar: 'كلمة المرور غير صحيحة.' },
  deleteServer: { en: 'Delete server', ar: 'حذف الخادم' },
  moveToAnother: { en: 'Move to another server', ar: 'النقل إلى خادم آخر' },

  // Move to another server
  moveTo: { en: 'Move to', ar: 'النقل إلى' },
  rehearse: { en: 'Rehearse', ar: 'تجريب' },
  stepCheckOther: { en: 'Check the other server', ar: 'فحص الخادم الآخر' },
  stepRestore: { en: 'Restore the backup', ar: 'استعادة النسخة الاحتياطية' },
  stepDone: { en: 'Done', ar: 'تم' },
  rehearsed: {
    en: 'The rehearsal finished. Nothing was changed on the other server.',
    ar: 'اكتمل التجريب. لم يتغير شيء على الخادم الآخر.',
  },

  // Dashboard and About
  dashboardTitle: { en: 'Dashboard', ar: 'لوحة المتابعة' },
  version: { en: 'Version', ar: 'الإصدار' },
  copyExportCommand: { en: 'Copy the export command', ar: 'نسخ أمر التصدير' },

  // Backups
  noPlansYet: { en: 'No plans yet', ar: 'لا توجد خطط بعد' },
  createDbsPlan: { en: 'Create a django-dbs plan', ar: 'إنشاء خطة django-dbs' },
  addPlan: { en: 'Add plan', ar: 'إضافة خطة' },
  addPlanSubmit: { en: 'Add plan', ar: 'إضافة الخطة' },
  kindFolders: { en: 'Folders', ar: 'المجلدات' },
  kindExisting: { en: 'Existing files', ar: 'ملفات موجودة' },
  folders: { en: 'Folders', ar: 'المجلدات' },
  folder: { en: 'Folder', ar: 'المجلد' },
  pattern: { en: 'Pattern', ar: 'النمط' },
  schedule: { en: 'Schedule', ar: 'الجدولة' },
  daily: { en: 'Daily', ar: 'يوميا' },
  keepHere: { en: 'Keep here', ar: 'الاحتفاظ هنا' },
  planAdded: { en: 'Plan added.', ar: 'تمت إضافة الخطة.' },
  planDeleted: { en: 'Plan deleted.', ar: 'تم حذف الخطة.' },
  notRunYet: { en: 'Not run yet', ar: 'لم تعمل بعد' },
  succeeded: { en: 'Succeeded', ar: 'تم بنجاح' },
  noBackupsYet: { en: 'No backups yet', ar: 'لا توجد نسخ احتياطية بعد' },
  backUpNow: { en: 'Back up now', ar: 'نسخ احتياطي الآن' },
  backupRunning: {
    en: 'A backup is running. It continues if you leave this page.',
    ar: 'النسخ الاحتياطي قيد التنفيذ. ويستمر حتى إذا غادرت هذه الصفحة.',
  },
  backupFinished: { en: 'Backup finished.', ar: 'اكتمل النسخ الاحتياطي.' },
  checkPassed: { en: 'Check passed.', ar: 'نجح الفحص.' },
  backupDeleted: { en: 'Backup deleted.', ar: 'تم حذف النسخة الاحتياطية.' },
  deletionUndone: { en: 'Deletion undone.', ar: 'تم التراجع عن حذف النسخة الاحتياطية.' },
  backupUploaded: { en: 'Backup uploaded.', ar: 'تم رفع النسخة الاحتياطية.' },
  uploadBackup: { en: 'Upload a backup', ar: 'رفع نسخة احتياطية' },
  undo: { en: 'Undo', ar: 'تراجع' },
  dismiss: { en: 'Close', ar: 'إغلاق' },
  download: { en: 'Download', ar: 'تنزيل' },
  verify: { en: 'Verify', ar: 'تحقق من' },
  delete: { en: 'Delete', ar: 'حذف' },
  run: { en: 'Run', ar: 'تشغيل' },
  now: { en: 'now', ar: 'الآن' },
  verified: { en: 'Verified', ar: 'تم التحقق' },
  structureChecked: { en: 'Structure checked', ar: 'تم فحص البنية' },
  sealedStored: { en: 'Stored', ar: 'محفوظ' },
  sealedIntact: { en: 'Intact', ar: 'سليم' },
  uploaded: { en: 'Uploaded', ar: 'مرفوع' },
  collected: { en: 'Collected: 2.', ar: 'عدد الملفات التي تم جمعها: 2.' },
  nothingNew: { en: 'Nothing new to collect.', ar: 'لا توجد ملفات جديدة لجمعها.' },

  // Files
  uploadFile: { en: 'Upload a file', ar: 'رفع ملف' },
  newFolder: { en: 'New folder', ar: 'مجلد جديد' },
  createFolder: { en: 'Create folder', ar: 'إنشاء المجلد' },
  enterFolderName: { en: 'Enter a name for the folder.', ar: 'أدخل اسما للمجلد.' },
  allowedFolder: { en: 'Allowed folder', ar: 'المجلد المسموح به' },
  folderPath: { en: 'Folder path', ar: 'مسار المجلد' },
  openFolder: { en: 'Open folder', ar: 'فتح المجلد' },
  fileUploaded: { en: 'File uploaded.', ar: 'تم رفع الملف.' },
  folderCreated: { en: 'Folder created.', ar: 'تم إنشاء المجلد.' },
  folderDeleted: { en: 'Folder deleted.', ar: 'تم حذف المجلد.' },
  fileDeleted: { en: 'File deleted.', ar: 'تم حذف الملف.' },
  deleteThisFolder: { en: 'Delete this folder?', ar: 'حذف هذا المجلد؟' },
  deleteThisFile: { en: 'Delete this file?', ar: 'حذف هذا الملف؟' },
  outsideAllowed: {
    en: "This path is outside the server's allowed folders.",
    ar: 'هذا المسار خارج المجلدات المسموح بها على الخادم.',
  },
  tryAgain: { en: 'Try again', ar: 'إعادة المحاولة' },

  // .env file
  pullNow: { en: 'Pull now', ar: 'جلب الآن' },
  noVersionsYet: { en: 'No versions yet', ar: 'لا توجد إصدارات بعد' },
  newVersionKept: { en: 'New version kept.', ar: 'تم حفظ إصدار جديد.' },
  noChange: { en: 'No change since the last version.', ar: 'لا تغيير منذ آخر إصدار.' },
  selectedVersion: { en: 'Selected version', ar: 'الإصدار المحدد' },
  valueHidden: { en: 'Value hidden', ar: 'القيمة مخفية' },
  showValues: { en: 'Show values', ar: 'إظهار القيم' },
  hideValues: { en: 'Hide values', ar: 'إخفاء القيم' },
  fileContent: { en: 'File content', ar: 'محتوى الملف' },
  compare: { en: 'Compare with the previous version', ar: 'مقارنة بالإصدار السابق' },
  changesSince: { en: 'Changes since the previous version', ar: 'التغييرات منذ الإصدار السابق' },
  addedKeys: { en: 'Added keys', ar: 'مفاتيح جديدة' },
  firstVersion: { en: 'This is the first version kept.', ar: 'هذا أول إصدار محفوظ.' },
  pushThis: { en: 'Push this version to the server', ar: 'إرسال هذا الإصدار إلى الخادم' },
  replaceEnv: { en: 'Replace the .env file on the server?', ar: 'استبدال ملف متغيرات البيئة على الخادم؟' },
  continue: { en: 'Continue', ar: 'متابعة' },
  pushVersion: { en: 'Push version', ar: 'إرسال الإصدار' },
  versionPushed: { en: 'Version pushed to the server.', ar: 'تم إرسال الإصدار إلى الخادم.' },
  pushed: { en: 'Pushed', ar: 'تم إرساله' },

  // Activity
  activityTitle: { en: 'Activity', ar: 'النشاط' },
  status: { en: 'Status', ar: 'الحالة' },
  action: { en: 'Action', ar: 'الإجراء' },
  failed: { en: 'Failed', ar: 'فشل' },
  actionSignIn: { en: 'Sign in', ar: 'تسجيل الدخول' },
  actionFailedSignIn: { en: 'Failed sign-in', ar: 'محاولة تسجيل دخول فاشلة' },
  actionAddServer: { en: 'Add server', ar: 'إضافة خادم' },
  actionConnectionCheck: { en: 'Connection check', ar: 'فحص الاتصال' },
  actionShowPassphrase: {
    en: 'Show backup passphrase',
    ar: 'إظهار عبارة مرور النسخ الاحتياطية',
  },
} as const satisfies Record<string, { en: string; ar: string }>;

export function copyIn(lang: Lang): (key: CopyKey) => string {
  return (key) => COPY[key][lang];
}
